# Generated by Django 5.2.7 on 2025-10-27 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('club_home', 'Club Home'), ('club_away', 'Club Away'), ('national', 'National Team'), ('training', 'Training'), ('other', 'Other')], default='club_home', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=249.99, help_text='Price in USD (e.g., 249.99)', max_digits=10)),
                ('thumbnail', models.URLField(blank=True, help_text='URL gambar produk', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('item_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
